stages:
  - build
  - deploy

#  docker-in-docker
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_user_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/user_service:latest -f ./user_service/Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/user_service:latest

build_plant_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/plant_service:latest -f ./plant_service/Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/plant_service:latest

build_simulation_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/simulation_service:latest -f ./simulation_service/Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/simulation_service:latest

build_websocket_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/websocket_service:latest -f ./websocket_service/Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/websocket_service:latest

build_bug_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/bug_service:latest -f ./bug_service/Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/bug_service:latest

build_main:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienphc0512/greenhouse-lab/main:latest -f ./Dockerfile .
    - docker push registry.gitlab.com/tienphc0512/greenhouse-lab/main:latest


deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt-get update
    - apt-get install -y openssh-client
    - chmod 400 $SSH_PRIVATE_KEY
    - docker login registry.gitlab.com -u Tienphc0512 -p glft-2-FzE6mQuKSsrG9R7fCx
  script:
    - ssh -i $SSH_PRIVATE_KEY -o StrictHostKeyChecking=no phengtin0512@35.247.188.150 "cd ~/greenhouse-lab && docker-compose pull && docker-compose up -d"
