stages:
  - build
  - deploy

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_user_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/user_service:latest ./user_service
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/user_service:latest

build_plant_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/plant_service:latest ./plant_service
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/plant_service:latest

build_simulation_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/simulation_service:latest ./simulation_service
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/simulation_service:latest

build_websocket_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/websocket_service:latest ./websocket_service
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/websocket_service:latest

build_bug_service:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/bug_service:latest ./bug_service
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/bug_service:latest

build_main_app:
  stage: build
  script:
    - docker build -t registry.gitlab.com/tienpham/greenhouse-lab/main_app:latest ./main
    - docker push registry.gitlab.com/tienpham/greenhouse-lab/main_app:latest

deploy:
  stage: deploy
  script:
    - ssh phengtin0512@35.198.252.247 "cd ~/greenhouse && docker-compose pull && docker-compose up -d"
