services:
  user_service:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/user_service:latest
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: always

  plant_service:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/plant_service:latest
    ports:
      - "5002:5002"
    depends_on:
      - db
    restart: always

  simulation_service:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/simulation_service:latest
    ports:
      - "5003:5003"
    depends_on:
      - db
      - plant_service
    restart: always

  websocket_service:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/websocket_service:latest
    ports:
      - "5004:5004"
    restart: always
  
  bug_service:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/bug_service:latest
    ports:
      - "5010:5010"
    depends_on:
      - db
    restart: always

  main_app:
    image: registry.gitlab.com/tienphc0512/greenhouse-labv2/main:latest
    ports:
      - "5000:5000"
    depends_on:
      - user_service
      - plant_service
      - simulation_service
      - websocket_service
    restart: always

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
